Add pathway
adityajain-deqode/grapghql-training pull request #2
Opened 2021-11-02 10:57 UTC by adityajain-deqode

- Add pathway gem
- Add dry-validation
- Add operations and integrate with mutation.

2021-11-02 12:30 UTC, jsamant123 requested changes

2021-11-02 12:30 UTC, jsamant123 commented on app/graphql/operations/link_operation/create.rb
> +      def create_link(params)
@adityajain-deqode `#create_link` can be a private method.

2021-11-02 12:30 UTC, jsamant123 commented on app/graphql/operations/link_operation/update.rb
> +      def update_link(params, **)
@adityajain-deqode `#update_link` can be a private method.

2021-11-02 12:30 UTC, jsamant123 commented on app/graphql/operations/link_operation/update.rb
> +        if link.update(params[:input])
@adityajain-deqode `update_link` can be modified as below:
```
def update_link(params, **)
  return link if link.update(params[:input])

  link.errors
end
```

2021-11-03 04:34 UTC, nyadav-deqode approved these changes

2021-11-03 04:34 UTC, merged